### ISSUE TITLE
使用npm run webpack时遇到其他问题。使用static声明变量是哪的语法，就这一句声明不通过

### ISSUE THREAD

**Issue by jackiewillen** [coderzzp/vue-come-true#1]
ERROR in ./src/vue/dep.js
Module parse failed: /Users/jackiewillen/Documents/work/myGitHub/vue-come-true/vue-come-true-Second/src/vue/dep.js Unexpected token (6:17)
You may need an appropriate loader to handle this file type.
|
| export default class Dep {
|     static target;
|
|     constructor() {
 @ ./src/vue/watcher.js 1:0-23
 @ ./src/vue/MVVM.js

**Comment by coderzzp** [comment]
抱歉，因为最近一直没有登录github，对您造成的困扰我表示非常抱歉，现在问题已经解决了，可以更新一下代码。另外说明一下static是ES6语法对象的静态属性，建议去看一下阮一峰的ES6介绍，如果还有不懂得欢迎随时联系我
